### ISSUE TITLE
Nodes with whitespace in title are not visualized properly on hover

### ISSUE THREAD

**Issue by Likbjorn** [Likbjorn/tag-cloud#33]
We use `"#" + node.title` selector to select node to highlight. But if title contains whitespaces, node can't be found.
We can use unique id's instead of titles for each node to avoid it.

**Comment by Cobolock** [comment]
FIxed in [a patch](https://github.com/Likbjorn/tag-cloud/commit/0a5cfffd4c7d9ec9c04eb920f6ca757777cfaf4a)
