### ISSUE TITLE
Set SVG container to window size

### ISSUE THREAD

**Issue by Likbjorn** [Likbjorn/tag-cloud#6]
- [x] SVG container is of viewport size
- [x] SVG resizes when viewport size changes
- [x] SVG container keeps ratio when resized
- [x] Objects sizes depend on relative "pixel" size of the resizeable container

**Comment by Cobolock** [comment]
- [ ] SVG container keeps ratio when resized
- [ ] Objects sizes depend on relative "pixel" size of the resizeable container

**Comment by Likbjorn** [comment]
Updated issue description

**Comment by Likbjorn** [comment]
Done in #23

**Comment by Likbjorn** [comment]
Done in #23
