### ISSUE TITLE
Bubbles should invite user to interact with them

### ISSUE THREAD

**Issue by Likbjorn** [Likbjorn/tag-cloud#8]
- [x] Add attraction force for nearest bubble
- [x] Color shifts when mouse approaches
- [x] Bubbles gravitate back to their place when mouse leaves the triggering area
- [x] Do this for all nodes around cursor, not the closest one

EDIT: add tasks from Cobold
EDIT 2: we want all nodes to react, not the closest one

**Comment by Cobolock** [comment]
- [x] Color shifts when mouse approaches

- [x] Bubbles gravitate back to their place when mouse leaves the triggering area

**Comment by Likbjorn** [comment]
> Color shifts when mouse approaches

Checkout voronoi diagram (available in d3.js). It will allow you to trigger only the closest bubble and avoid situations, when trigger areas of different bubbles collide.

**Comment by Cobolock** [comment]
> Checkout voronoi diagram (available in d3.js). It will allow you to trigger only the closest bubble and avoid situations, when trigger areas of different bubbles collide.

We need every bubble in the unspecified range to react with mouse. That may mean one or all of them.

**Comment by Likbjorn** [comment]
We need to describe how bubbles will interact with user in detail before creating specific tasks. I don't have a good understanding of it yet.

What we may do. When cursor is close or when cursor is over the element:

- Add animation when cursor is close: shake, pulse, rotate or move towards cursor;
- Modify color: pulse, change to specified color;
- Add more elements: particles around bubble, ring around it, highlight with bloom or shadow
- etc.

Definition of "close" selection: either all elements within specified range or only the closest one.
